export const sampleJobData = [
    {
        id: 1, // Note: Backend uses _id, Frontend sample uses id (handled in components via checks)
        company: "Suguna Foods",
        title: "Senior Software Engineer",
        rating: 4.0,
        reviews: "1.4K+",
        logoUrl: "https://logo.clearbit.com/sugunafoods.co.in",
        description: "Hiring for multiple software development roles. Join our team to innovate in the food tech industry. Experience with microservices is a plus.",
        skills: ["Java", "Spring Boot", "SQL", "Microservices"],
        location: "Coimbatore, India",
        applyLink: "https://www.sugunafoods.co.in/careers",
        postedDate: new Date(new Date().setDate(new Date().getDate()-1)).toISOString() // 1 day ago
    },
    {
        id: 2,
        company: "IndiaMART",
        title: "Frontend Developer (React)",
        rating: 3.6,
        reviews: "5.6K+",
        logoUrl: "https://logo.clearbit.com/indiamart.com",
        description: "Looking for talented engineers to build the future of B2B e-commerce in India. Must have strong proficiency in React.js and Redux.",
        skills: ["React", "Node.js", "Redux", "JavaScript"],
        location: "Noida, India",
        applyLink: "https://careers.indiamart.com/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-2)).toISOString() // 2 days ago
    },
    {
        id: 3,
        company: "Reckitt",
        title: "Data Scientist",
        rating: 3.9,
        reviews: "1.7K+",
        logoUrl: "https://logo.clearbit.com/reckitt.com",
        description: "Join a global FMCG leader. We have openings for data scientists to analyze consumer behavior trends using machine learning models.",
        skills: ["Python", "Data Science", "Machine Learning", "Pandas"],
        location: "Gurugram, India",
        applyLink: "https://www.reckitt.com/careers/",
        postedDate: new Date().toISOString() // Today
    },
    {
        id: 4,
        company: "Tech Mahindra",
        title: "Cloud Solutions Architect",
        rating: 4.1,
        reviews: "10K+",
        logoUrl: "https://logo.clearbit.com/techmahindra.com",
        description: "Explore opportunities in cloud computing with a global IT giant. You will design scalable cloud architectures on AWS.",
        skills: ["Cloud", "AWS", "Docker", "Kubernetes"],
        location: "Pune, India",
        applyLink: "https://careers.techmahindra.com/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-1)).toISOString()
    },
    {
        id: 5,
        company: "Zoho Corporation",
        title: "Product Designer (UI/UX)",
        rating: 4.4,
        reviews: "3.2K+",
        logoUrl: "https://logo.clearbit.com/zoho.com",
        description: "We are looking for a creative Product Designer to design intuitive user experiences for our suite of business applications.",
        skills: ["UI/UX", "Figma", "Design Systems", "Prototyping"],
        location: "Chennai, India",
        applyLink: "https://www.zoho.com/careers/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-3)).toISOString()
    },
    {
        id: 6,
        company: "Freshworks",
        title: "Backend Engineer (Ruby/Java)",
        rating: 4.2,
        reviews: "2.1K+",
        logoUrl: "https://logo.clearbit.com/freshworks.com",
        description: "Scale our SaaS products to millions of users. Deep understanding of backend technologies and API design is required.",
        skills: ["Ruby", "Java", "REST API", "PostgreSQL"],
        location: "Chennai, India",
        applyLink: "https://www.freshworks.com/company/careers/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-4)).toISOString()
    },
    {
        id: 7,
        company: "Flipkart",
        title: "SDE-II",
        rating: 4.3,
        reviews: "8K+",
        logoUrl: "https://logo.clearbit.com/flipkart.com",
        description: "Solve complex e-commerce challenges at scale. Work on high-performance distributed systems.",
        skills: ["Java", "System Design", "Distributed Systems", "Kafka"],
        location: "Bengaluru, India",
        applyLink: "https://www.flipkartcareers.com/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-1)).toISOString()
    },
    {
        id: 8,
        company: "TCS",
        title: "Cybersecurity Analyst",
        rating: 3.8,
        reviews: "15K+",
        logoUrl: "https://logo.clearbit.com/tcs.com",
        description: "Monitor and secure enterprise networks. Experience with SIEM tools and vulnerability assessment is required.",
        skills: ["Cybersecurity", "Network Security", "SIEM", "Ethical Hacking"],
        location: "Mumbai, India",
        applyLink: "https://www.tcs.com/careers",
        postedDate: new Date(new Date().setDate(new Date().getDate()-5)).toISOString()
    },
    {
        id: 9,
        company: "Wipro",
        title: "Full Stack Developer (.NET)",
        rating: 3.7,
        reviews: "12K+",
        logoUrl: "https://logo.clearbit.com/wipro.com",
        description: "Develop enterprise-grade web applications using .NET Core and Angular. Strong C# skills needed.",
        skills: [".NET", "C#", "Angular", "SQL Server"],
        location: "Hyderabad, India",
        applyLink: "https://careers.wipro.com/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-2)).toISOString()
    },
    {
        id: 10,
        company: "Swiggy",
        title: "Mobile App Developer (Flutter)",
        rating: 4.0,
        reviews: "1.2K+",
        logoUrl: "https://logo.clearbit.com/swiggy.com",
        description: "Build the next generation of food delivery apps. Proficiency in Flutter and Dart is essential.",
        skills: ["Flutter", "Dart", "Mobile Dev", "Firebase"],
        location: "Bengaluru, India",
        applyLink: "https://careers.swiggy.com/",
        postedDate: new Date(new Date().setDate(new Date().getDate()-1)).toISOString()
    }
];